services:
  db:
    image: postgres:latest
    container_name: hoopgrade-db
    restart: always
    ports:
      - "5001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hoopgrade_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
